## Import Modules

In [52]:
import pandas as pd
import numpy as np

## Load the dataset and see preview

In [53]:
f_news=pd.read_csv('data.csv')
f_news.head()

URLs  \
0  http://www.bbc.com/news/world-us-canada-414191...   
1  https://www.reuters.com/article/us-filmfestiva...   
2  https://www.nytimes.com/2017/10/09/us/politics...   
3  https://www.reuters.com/article/us-mexico-oil-...   
4  http://www.cnn.com/videos/cnnmoney/2017/10/08/...   

                                            Headline  \
0         Four ways Bob Corker skewered Donald Trump   
1  Linklater's war veteran comedy speaks to moder...   
2  Trump’s Fight With Corker Jeopardizes His Legi...   
3  Egypt's Cheiron wins tie-up with Pemex for Mex...   
4        Jason Aldean opens 'SNL' with Vegas tribute   

                                                Body  Label  
0  Image copyright Getty Images\nOn Sunday mornin...      1  
1  LONDON (Reuters) - “Last Flag Flying”, a comed...      1  
2  The feud broke into public view last week when...      1  
3  MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...      1  
4  Country singer Jason Aldean, who was performin...      1

## Playing with the dataset by doing some stuff

In [54]:
f_news=f_news.drop(['URLs'],axis=1)
f_news=f_news.dropna()
f_news.head()

Headline  \
0         Four ways Bob Corker skewered Donald Trump   
1  Linklater's war veteran comedy speaks to moder...   
2  Trump’s Fight With Corker Jeopardizes His Legi...   
3  Egypt's Cheiron wins tie-up with Pemex for Mex...   
4        Jason Aldean opens 'SNL' with Vegas tribute   

                                                Body  Label  
0  Image copyright Getty Images\nOn Sunday mornin...      1  
1  LONDON (Reuters) - “Last Flag Flying”, a comed...      1  
2  The feud broke into public view last week when...      1  
3  MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...      1  
4  Country singer Jason Aldean, who was performin...      1

## Taking only the first 2000 entries of the dataset

In [55]:
f_news=f_news[0:2000]
X=f_news.iloc[:,:-1].values
Y=f_news.iloc[:,-1].values
X[0]
Y[0]

1

## Using CountVectorizer from sklearn to convert text to number format

In [56]:
from sklearn.feature_extraction.text import CountVectorizer
CV=CountVectorizer(max_features=5000)
mat_body=CV.fit_transform(X[:,1]).todense()
mat_body

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [57]:
CV_head=CountVectorizer(max_features=5000)
mat_head=CV_head.fit_transform(X[:,0]).todense()
mat_head

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Making mat_body and mat_head Stacked horizontally

In [58]:
X_mat=np.hstack((mat_head,mat_body))

## Training and Testing the model

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_mat,Y,test_size=0.2,random_state=0)

## Building the model using Decision Tree

In [60]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy')
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

## Finally building a confusion matrix and checking results

In [61]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,Y_pred)

array([[196,   9],
       [ 14, 181]], dtype=int64)

## Calculating Accuracy Of the model

In [63]:
Accuracy=(196+181)/(196+181+14+9)
Accuracy*100

94.25